In [11]:
# Have user select excel sheet with needed data.
import tkinter as tk
from tkinter import filedialog

root = tk.Tk()
root.lift()
root.withdraw()

# This code block will open a specific file. (Uncomment the lines after this comment to use them.)
#print('Opening dialogue box for file selection. Please choose a file.')
#file_path = filedialog.askopenfilename()
#print('File selected:')

# This code block will get a directory path. (Uncomment the lines after this comment to use them.)
print('Opening dialogue box for folder selection. Please choose a folder.')
file_path = filedialog.askdirectory()
print('Folder selected:')

print(file_path)

Opening dialogue box for folder selection. Please choose a folder.
Folder selected:
C:/Users/lwolf/Desktop/MY PROJECTS/exerPythCombineFiles/FileTypes/FileTypes

In [12]:
# Make sure correct files are recognized.

import os
import pandas as pd

# List the files in the directory.
files = os.listdir(file_path)
print(files)

# List of file types we want to add
file_types = ['xlsx','csv','json','xml']

# create a list of files for each file type
files_csv = [f for f in files if f[-3:] == 'csv']
files_xlsx = [f for f in files if f[-4:] == 'xlsx']
files_json = [f for f in files if f[-4:] == 'json']
files_xml = [f for f in files if f[-3:] == 'xml']

print('CSVfiles: ', files_csv, '\nExcel files: ', files_xlsx, '\nJSON files: ', files_json, '\nXML files: ', files_xml)

['.ipynb_checkpoints', 'Aunt.csv', 'boys.xlsx', 'Combine multiple file types with same columns into dataframe.ipynb', 'Combine multiple file types with same columns into dataframe.py', 'CSVtest.csv', 'CSVtest2.csv', 'CSVtest3.csv', 'EXCELtest.xlsx', 'EXCELtest2.xlsx', 'EXCELtest3.xlsx', 'girls.xlsx', 'Joan.json', 'JSONtest.json', 'JSONtest2.json', 'JSONtest3.json', 'JSONtest4.json', 'Matthew.xml', 'peter.json', 'stephanie.xml', 'uncles.csv', 'XMLtest.xml', 'XMLtest2.xml', 'XMLtest3.xml', 'XMLtest4.xml']
CSVfiles:  ['Aunt.csv', 'CSVtest.csv', 'CSVtest2.csv', 'CSVtest3.csv', 'uncles.csv']
Excel files:  ['boys.xlsx', 'EXCELtest.xlsx', 'EXCELtest2.xlsx', 'EXCELtest3.xlsx', 'girls.xlsx']
JSON files:  ['Joan.json', 'JSONtest.json', 'JSONtest2.json', 'JSONtest3.json', 'JSONtest4.json', 'peter.json']
XML files:  ['Matthew.xml', 'stephanie.xml', 'XMLtest.xml', 'XMLtest2.xml', 'XMLtest3.xml', 'XMLtest4.xml']

In [13]:
import json
import requests 
import xml.etree.ElementTree as ET

# Iterate through the files in the directory and append each one into the dataframe.
# This will only work correctly if the files have the exact same column names.
df_list = []
for f in files_csv:
    data = pd.read_csv(str(file_path) + '/' + str(f), index_col=None, header=0)
    data['Source'] = f
    df_list.append(data)
    
for f in files_xlsx:
    data = pd.read_excel(str(file_path) + '/' + str(f))
    data['Source'] = f
    df_list.append(data)
    
# Iterate through the json files and add data from each to a list.
json_list = []
for f in files_json:
    with open(str(file_path) + '/' + str(f)) as json_file:
        json_obj = json.load(json_file)
        json_obj['Source'] = f
        json_list.append(json_obj.copy())
# Turn the combined list into a dataframe.
data = pd.DataFrame(json_list)
# Add the data frame to the list of dataframes.
df_list.append(data)
    
# Iterate through the xml files and add data from each to a list.
xml_list = []
for f in files_xml:
    # create element tree object 
    tree = ET.parse(str(file_path) + '/' + str(f))
    # get root element 
    root = tree.getroot()
    # create dictionary from XML tags and values
    itemdict = {}
    for item in root:
        itemdict[item.tag] = item.text
    itemdict['Source'] = f
    xml_list.append(itemdict.copy())
# Turn the combined list into a dataframe.
data = pd.DataFrame(xml_list)
# Add the data frame to the list of dataframes.
df_list.append(data)

# Combine all the data frames in the list into a single data frame.    
df =  pd.concat(df_list, axis=0, ignore_index=True, sort=False)

# See how many rows the data frame has.
print(len(df.index))

# Show the data in the data frame.
df

32

               name                 date height weight           Source
0       Holli Gayle           11/12/1974    170     50         Aunt.csv
1         Nina Shae            9/24/1973    150     35         Aunt.csv
2        Jack Smith             4/1/2019    185     91      CSVtest.csv
3        Jack Black             4/2/2019    183     91      CSVtest.csv
4      Brock Bricks            4/10/2019    185     95     CSVtest2.csv
5        Jack Brack             6/7/2019    172     91     CSVtest2.csv
6       Holli Gayle           11/12/1974    170     50     CSVtest3.csv
7         Nina Shae            9/24/1973    150     35     CSVtest3.csv
8     nathan daniel           10/31/1973    160     80       uncles.csv
9     shawn Michael           11/17/1973    150     80       uncles.csv
10       Noah Riley  2002-01-15 00:00:00    180     74        boys.xlsx
11    Doanven James  1996-03-11 00:00:00    170     86        boys.xlsx
12        Jen Smith  2019-05-02 00:00:00    153     50   EXCELtest.xlsx
13        Sam Smith  2019-01-02 00:00:00    160     55   EXCELtest.xlsx
14      Rock Royden  2019-05-02 00:00:00    160     52  EXCELtest2.xlsx
15    Brandon Snads  2019-10-02 00:00:00    175     80  EXCELtest2.xlsx
16       Noah Riley  2002-01-15 00:00:00    180     74  EXCELtest3.xlsx
17    Doanven James  1996-03-11 00:00:00    170     86  EXCELtest3.xlsx
18        sidney jo  2004-03-09 00:00:00    170     58       girls.xlsx
19           kim jo  2005-01-10 00:00:00    150     56       girls.xlsx
20       Joan Gayle           12/11/1955    170     75        Joan.json
21       Jane Smith           09/02/2019    170     75    JSONtest.json
22     Jane Jackson           09/03/2019    172     74   JSONtest2.json
23    Becky Jackson           04/03/2019    165     70   JSONtest3.json
24       Joan Gayle           12/11/1955    170     75   JSONtest4.json
25     Peter Parker           09/02/2019    145     35       peter.json
26  Matthew Garrett           07/10/1985    195   None      Matthew.xml
27    stephanie sue           05/08/1989    120     50    stephanie.xml
28       John Smith           02/08/2019    180    100      XMLtest.xml
29      John Smithe           03/08/2019    185    101     XMLtest2.xml
30     Brett Smithe           05/08/2019    179     99     XMLtest3.xml
31  Matthew Garrett           07/10/1985    195   None     XMLtest4.xml

In [14]:
# Save the dataframe to a new combined csv file.

# Add today's date to the name of the new file.
from datetime import date
today = date.today()
print(today)

filename = str(file_path) + '/' + 'NewCombinedFile_' + str(today) + '.csv'
print(filename)

df.to_csv(filename, index=False)
print('File saved.')

2020-10-13
C:/Users/lwolf/Desktop/MY PROJECTS/exerPythCombineFiles/FileTypes/FileTypes/NewCombinedFile_2020-10-13.csv
File saved.